#!/usr/bin/env bash
# Script that installs and configures HAProxy load balancer on Ubuntu 16.04+

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Backup the original configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Write new HAProxy configuration
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend web_back

backend web_back
    balance roundrobin
    server 6810-web-01 54.161.135.230:80 check
    server 6810-web-02 13.221.22.9:80 check
EOF'

# Restart HAProxy service
sudo service haproxy restart
